server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: changeit

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://login.microsoftonline.com/<tenant-id>/v2.0 # requires: accessTokenAcceptedVersion: 2
#      client:
#        registration:
#          azure:
#            provider: azure
#            client-id: <client-id>
#            client-secret: <secret>
#            scope:
#              - openid
#              - profile
#              - api://demo.dev/user
#            redirect-uri: "{baseUrl}/login/oauth2/callback/azure"
#        provider:
#          azure:
#            # https://login.microsoftonline.com/<tenant-id>/v2.0/.well-known/openid-configuration
#            issuer-uri: https://login.microsoftonline.com/<tenant-id>/v2.0
